# Generated by Django 4.2.26 on 2025-11-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userinvitation_teammember_roletemplate'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensereport',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mileagelog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mileage_logs', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'user', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'status'], name='expenses_ex_company_56b42f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'date'], name='expenses_ex_company_c0780e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'user'], name='expenses_ex_company_224535_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['company', 'is_active'], name='expenses_ex_company_b10a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['company', 'user'], name='expenses_ex_company_0ae721_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['company', 'status'], name='expenses_ex_company_bb4477_idx'),
        ),
        migrations.AddIndex(
            model_name='expensereport',
            index=models.Index(fields=['company', 'user'], name='expenses_ex_company_6817d0_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagelog',
            index=models.Index(fields=['company', 'date'], name='expenses_mi_company_353c18_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagelog',
            index=models.Index(fields=['company', 'user'], name='expenses_mi_company_228247_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'is_active'], name='expenses_ve_company_b8bb04_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'name'], name='expenses_ve_company_199608_idx'),
        ),
    ]
