# Generated by Django 4.2.26 on 2025-12-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expensecategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
    ]
