# Generated by Django 5.1.3 on 2025-08-01 16:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('credit_card', 'Credit Card'), ('line_of_credit', 'Line of Credit'), ('other', 'Other')], default='checking', max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_reconciled_date', models.DateField(blank=True, null=True)),
                ('last_reconciled_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_reconciliation_bankaccount',
                'ordering': ['bank_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('beginning_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statement_period_start', models.DateField()),
                ('statement_period_end', models.DateField()),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('processing', 'Processing'), ('reconciled', 'Reconciled'), ('partially_reconciled', 'Partially Reconciled'), ('discrepancy', 'Discrepancy Found')], default='imported', max_length=20)),
                ('reconciliation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='bank_reconciliation.bankaccount')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'db_table': 'bank_reconciliation_bankstatement',
                'ordering': ['-statement_date'],
                'unique_together': {('bank_account', 'statement_date')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('interest', 'Interest'), ('dividend', 'Dividend'), ('check', 'Check'), ('debit_card', 'Debit Card'), ('ach', 'ACH'), ('wire', 'Wire Transfer'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('check_number', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reconciliation_status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('matched', 'Matched'), ('cleared', 'Cleared'), ('disputed', 'Disputed'), ('void', 'Void')], default='unreconciled', max_length=20)),
                ('reconciled_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_reconciliation.bankstatement')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'db_table': 'bank_reconciliation_banktransaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('description_contains', 'Description Contains'), ('description_exact', 'Description Exact Match'), ('amount_exact', 'Amount Exact Match'), ('amount_range', 'Amount Range'), ('check_number', 'Check Number'), ('reference_number', 'Reference Number'), ('combined', 'Combined Criteria')], max_length=20)),
                ('description_pattern', models.CharField(blank=True, max_length=500)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('check_number_pattern', models.CharField(blank=True, max_length=50)),
                ('reference_pattern', models.CharField(blank=True, max_length=100)),
                ('auto_match', models.BooleanField(default=False)),
                ('confidence_threshold', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reconciliation_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Rule',
                'verbose_name_plural': 'Reconciliation Rules',
                'db_table': 'bank_reconciliation_reconciliationrule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('starting_book_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ending_book_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transactions_matched', models.IntegerField(default=0)),
                ('transactions_unmatched', models.IntegerField(default=0)),
                ('adjustments_made', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='bank_reconciliation.bankaccount')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to='bank_reconciliation.bankstatement')),
                ('reconciled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconciliation Session',
                'verbose_name_plural': 'Reconciliation Sessions',
                'db_table': 'bank_reconciliation_reconciliationsession',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bank_error', 'Bank Error'), ('book_error', 'Book Error'), ('outstanding_check', 'Outstanding Check'), ('deposit_in_transit', 'Deposit in Transit'), ('bank_fee', 'Bank Fee'), ('interest_earned', 'Interest Earned'), ('nsf_check', 'NSF Check'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('affects_bank_balance', models.BooleanField(default=False)),
                ('affects_book_balance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('reference_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='bank_reconciliation.banktransaction')),
                ('reconciliation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='bank_reconciliation.reconciliationsession')),
            ],
            options={
                'verbose_name': 'Reconciliation Adjustment',
                'verbose_name_plural': 'Reconciliation Adjustments',
                'db_table': 'bank_reconciliation_reconciliationadjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_date'], name='bank_reconc_transac_d48c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reconciliation_status'], name='bank_reconc_reconci_78ea55_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['amount'], name='bank_reconc_amount_875181_idx'),
        ),
    ]
