from django.contrib import admin
from .models import (
    AccountType, Account, JournalEntry, JournalEntryLine,
    FinancialPeriod, FinancialStatement
)


@admin.register(AccountType)
class AccountTypeAdmin(admin.ModelAdmin):
    list_display = ['code', 'name', 'category', 'subtype', 'is_active']
    list_filter = ['category', 'is_active']
    search_fields = ['code', 'name']
    ordering = ['code']


class JournalEntryLineInline(admin.TabularInline):
    model = JournalEntryLine
    extra = 2
    fields = ['account', 'description', 'debit', 'credit']


@admin.register(Account)
class AccountAdmin(admin.ModelAdmin):
    list_display = ['account_number', 'account_name', 'account_type', 'current_balance', 'is_active', 'user']
    list_filter = ['account_type__category', 'is_active', 'is_system_account']
    search_fields = ['account_number', 'account_name', 'user__username']
    ordering = ['account_number']
    readonly_fields = ['created_at', 'updated_at']


@admin.register(JournalEntry)
class JournalEntryAdmin(admin.ModelAdmin):
    list_display = ['entry_number', 'entry_date', 'entry_type', 'status', 'user', 'created_at']
    list_filter = ['status', 'entry_type', 'entry_date']
    search_fields = ['entry_number', 'description', 'user__username']
    ordering = ['-entry_date', '-created_at']
    readonly_fields = ['created_at', 'updated_at', 'posted_date']
    inlines = [JournalEntryLineInline]
    
    fieldsets = (
        ('Entry Information', {
            'fields': ('entry_number', 'entry_date', 'entry_type', 'status', 'user')
        }),
        ('Description', {
            'fields': ('description', 'reference')
        }),
        ('Related Documents', {
            'fields': ('invoice', 'expense')
        }),
        ('Audit Information', {
            'fields': ('posted_by', 'posted_date', 'created_at', 'updated_at')
        }),
    )


@admin.register(FinancialPeriod)
class FinancialPeriodAdmin(admin.ModelAdmin):
    list_display = ['name', 'period_type', 'start_date', 'end_date', 'is_closed', 'user']
    list_filter = ['period_type', 'is_closed']
    search_fields = ['name', 'user__username']
    ordering = ['-start_date']
    readonly_fields = ['created_at', 'updated_at', 'closed_date']


@admin.register(FinancialStatement)
class FinancialStatementAdmin(admin.ModelAdmin):
    list_display = ['statement_type', 'period', 'accounting_standard', 'generated_date', 'generated_by', 'user']
    list_filter = ['statement_type', 'accounting_standard', 'generated_date']
    search_fields = ['user__username', 'period__name']
    ordering = ['-generated_date']
    readonly_fields = ['generated_date', 'statement_data']
    
    fieldsets = (
        ('Statement Information', {
            'fields': ('statement_type', 'period', 'accounting_standard', 'user')
        }),
        ('Generated By', {
            'fields': ('generated_by', 'generated_date')
        }),
        ('Statement Data', {
            'fields': ('statement_data', 'notes'),
            'classes': ('collapse',)
        }),
    )
