# Generated by Django 4.2.23 on 2025-08-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
