# Generated by Django 4.2.26 on 2025-11-11 07:51

from django.db import migrations
from django.utils import timezone


def assign_companies_to_users(apps, schema_editor):
    """
    Create companies for users who don't have one and link them
    """
    User = apps.get_model('accounts', 'User')
    Company = apps.get_model('accounts', 'Company')
    UserCompany = apps.get_model('accounts', 'UserCompany')
    
    # Get all users
    users = User.objects.all()
    
    for user in users:
        # Check if user already has a company
        existing_user_company = UserCompany.objects.filter(user=user).first()
        
        if not existing_user_company:
            # Create a new company for this user
            full_name = f"{user.first_name} {user.last_name}".strip()
            company_name = f"{full_name or user.username}'s Company"
            
            company = Company.objects.create(
                name=company_name,
                email=user.email,
                fiscal_year_start=timezone.now().date().replace(month=1, day=1),
                currency='GHS',  # Ghana Cedis
                country='Ghana',
                created_by=user
            )
            
            # Link user to company
            UserCompany.objects.create(
                user=user,
                company=company,
                role='admin',
                is_active=True
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - doesn't delete companies as they might have data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_notification_preferences'),
    ]

    operations = [
        migrations.RunPython(assign_companies_to_users, reverse_migration),
    ]
