# Generated by Django 4.2.26 on 2025-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinvitation_teammember_roletemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
    ]
