# Generated by Django 4.2.26 on 2025-12-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_can_access_all_branches_alter_company_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'User Company Assignment', 'verbose_name_plural': 'User Company Assignments'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_access_all_branches',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_branch',
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Super admin can access all companies'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_companies',
            field=models.ManyToManyField(related_name='assigned_users', through='accounts.UserCompany', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Company Manager'), ('accountant', 'Accountant'), ('employee', 'Employee'), ('client', 'Client')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='permissions',
            field=models.JSONField(default=list, help_text='Specific permissions within the company'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('admin', 'Company Administrator'), ('manager', 'Company Manager'), ('accountant', 'Accountant'), ('employee', 'Employee'), ('viewer', 'Viewer')], default='employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Company Manager'), ('accountant', 'Accountant'), ('employee', 'Employee'), ('client', 'Client')], default='employee', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserBranch',
        ),
    ]
