# Generated by Django 4.2.26 on 2025-11-11 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinvitation_teammember_roletemplate'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_sku_f85905_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_barcode_3a77e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='inventory_p_name_f6a6a1_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'sku'), ('company', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company', 'is_active'], name='inventory_c_company_476e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'sku'], name='inventory_p_company_85d371_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='inventory_p_company_e5d498_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'name'], name='inventory_p_company_9c5d59_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'is_active'], name='inventory_s_company_7fd4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'name'], name='inventory_s_company_0db40d_idx'),
        ),
    ]
