# Generated by Django 4.2.26 on 2025-12-20 18:44

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug field for existing products."""
    Product = apps.get_model('inventory', 'Product')
    for product in Product.objects.all():
        if not product.slug and product.name:
            base_slug = slugify(product.name)
            slug = base_slug
            num = 1
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{base_slug}-{num}"
                num += 1
            product.slug = slug
            product.save()


def reverse_populate_slugs(apps, schema_editor):
    """Reverse migration - clear all slugs."""
    Product = apps.get_model('inventory', 'Product')
    Product.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_inventory_p_sku_f85905_idx_and_more'),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        # Populate existing records
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        # Then alter to add unique constraint
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
