# Generated by Django 4.2.26 on 2025-11-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
