# Generated by Django 4.2.23 on 2025-08-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ai_insights',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
