# Generated by Django 4.2.26 on 2025-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_customer_company_name_invoice_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='GHS', max_length=3),
        ),
    ]
