# Generated by Django 5.1.3 on 2025-07-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('expense_categorizer', 'Expense Categorizer'), ('fraud_detector', 'Fraud Detector'), ('payment_predictor', 'Payment Predictor'), ('cash_flow_forecaster', 'Cash Flow Forecaster'), ('receipt_processor', 'Receipt Processor'), ('anomaly_detector', 'Anomaly Detector')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('f1_score', models.FloatField(default=0)),
                ('prediction_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('cash_flow_prediction', 'Cash Flow Prediction'), ('expense_anomaly', 'Expense Anomaly Detection'), ('revenue_forecast', 'Revenue Forecast'), ('customer_risk', 'Customer Risk Assessment'), ('cost_optimization', 'Cost Optimization'), ('tax_optimization', 'Tax Optimization'), ('trend_analysis', 'Trend Analysis'), ('budget_variance', 'Budget Variance Analysis')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('recommendations', models.JSONField(default=list)),
                ('potential_impact', models.TextField(blank=True)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('user_feedback', models.TextField(blank=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('input_data', models.JSONField()),
                ('expected_output', models.JSONField()),
                ('actual_output', models.JSONField(default=dict)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user_correction', models.JSONField(default=dict)),
                ('model_version', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('expense_categorization', 'Expense Categorization'), ('invoice_follow_up', 'Invoice Follow-up'), ('receipt_processing', 'Receipt Processing'), ('bank_reconciliation', 'Bank Reconciliation'), ('fraud_detection', 'Fraud Detection'), ('tax_preparation', 'Tax Preparation'), ('report_generation', 'Report Generation')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_result', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('cash_flow', 'Cash Flow'), ('revenue', 'Revenue'), ('expenses', 'Expenses'), ('customer_churn', 'Customer Churn'), ('payment_delay', 'Payment Delay'), ('seasonal_trends', 'Seasonal Trends')], max_length=50)),
                ('predicted_values', models.JSONField(default=dict)),
                ('confidence_intervals', models.JSONField(default=dict)),
                ('prediction_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('model_used', models.CharField(max_length=100)),
                ('accuracy_score', models.FloatField(default=0)),
                ('actual_values', models.JSONField(default=dict)),
                ('variance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date'],
            },
        ),
    ]
