# Generated manually for sales app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),  # Assuming accounts app exists
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quarterly_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('boundaries', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sales Territory',
                'verbose_name_plural': 'Sales Territories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Rate'), ('tiered', 'Tiered')], default='percentage', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=6)),
                ('commission_tiers', models.JSONField(blank=True, default=dict)),
                ('monthly_quota', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quarterly_quota', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_quota', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='sales.salesrep')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reps', to='sales.salesterritory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Representative',
                'verbose_name_plural': 'Sales Representatives',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('email', 'Email Campaign'), ('social_media', 'Social Media'), ('event', 'Event'), ('advertisement', 'Advertisement'), ('partner', 'Partner'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('converted', 'Converted'), ('lost', 'Lost'), ('nurturing', 'Nurturing')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('probability', models.IntegerField(default=10)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('scoring_factors', models.JSONField(blank=True, default=dict)),
                ('conversion_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('ai_recommendations', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.salesrep')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.salesterritory')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_company', models.CharField(blank=True, max_length=100)),
                ('stage', models.CharField(choices=[('qualification', 'Qualification'), ('needs_analysis', 'Needs Analysis'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('verbal_commitment', 'Verbal Commitment'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='qualification', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('probability', models.IntegerField(default=10)),
                ('expected_close_date', models.DateField()),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('decision_factors', models.JSONField(blank=True, default=list)),
                ('decision_makers', models.JSONField(blank=True, default=list)),
                ('cost_of_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margin', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('next_step', models.CharField(blank=True, max_length=255)),
                ('next_step_date', models.DateField(blank=True, null=True)),
                ('ai_forecast', models.JSONField(blank=True, default=dict)),
                ('churn_risk', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='sales.lead')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='sales.salesrep')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.salesterritory')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal'), ('follow_up', 'Follow Up'), ('note', 'Note'), ('task', 'Task'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.opportunity')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.salesrep')),
            ],
            options={
                'verbose_name': 'Sales Activity',
                'verbose_name_plural': 'Sales Activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('earned_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.opportunity')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sales.salesrep')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-earned_date'],
            },
        ),
    ]
