# Generated by Django 5.1.3 on 2025-08-01 16:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-earned_date']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-expected_close_date'], 'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='salesactivity',
            options={'ordering': ['-activity_date'], 'verbose_name_plural': 'Sales Activities'},
        ),
        migrations.AlterModelOptions(
            name='salesrep',
            options={'verbose_name': 'Sales Representative'},
        ),
        migrations.AlterModelOptions(
            name='salesterritory',
            options={'verbose_name_plural': 'Sales Territories'},
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='commission',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.opportunity'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesrep'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrep'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='conversion_probability',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='probability',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('email_campaign', 'Email Campaign'), ('social_media', 'Social Media'), ('trade_show', 'Trade Show'), ('advertising', 'Advertising'), ('partner', 'Partner'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('nurturing', 'Nurturing')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesterritory'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='churn_risk',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='cost_of_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.lead'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='next_step',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='sales_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrep'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('qualification', 'Qualification'), ('needs_analysis', 'Needs Analysis'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='qualification', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesterritory'),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('proposal', 'Proposal'), ('follow_up', 'Follow Up'), ('note', 'Note'), ('task', 'Task')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.lead'),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.opportunity'),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='outcome',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesrep'),
        ),
        migrations.AlterField(
            model_name='salesactivity',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='commission_tiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate'), ('tiered', 'Tiered'), ('custom', 'Custom')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesrep'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesterritory'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesterritory',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesterritory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salesterritory',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
