# Generated by Django 4.2.23 on 2025-08-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_commission_options_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesactivity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.lead'),
        ),
    ]
