# Generated by Django 4.2.26 on 2025-11-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userinvitation_teammember_roletemplate'),
        ('sales', '0003_alter_salesactivity_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesrep',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reps', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesterritory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_territories', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='salesrep',
            unique_together={('company', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status'], name='sales_lead_company_381ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'assigned_to'], name='sales_lead_company_717585_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrep',
            index=models.Index(fields=['company', 'is_active'], name='sales_sales_company_e1fd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesterritory',
            index=models.Index(fields=['company', 'is_active'], name='sales_sales_company_0b43ba_idx'),
        ),
    ]
